jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 8
    - continue-on-error: true
      name: Set up Apache Maven Central
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: 8
        server-id: releases
        server-password: MAVEN_CENTRAL_TOKEN
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      env:
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_USERNAME: yuyijq
      name: Publish to Apache Maven Central
      run: mvn clean deploy -Prelease
name: deploy
on:
  repository_dispatch:
    types: trigger-ga___deploy.yml
